##Solano Quinte David Josue
print ("Pregunta 3")
n1 = int(input("ingrese el numero 1: "))
n2 = int(input("ingrese el numero 2: "))
n3 = int(input("ingrese el numero 3: "))
suma = int(n1+n2+n3)
resta = int(n1-n2-n3)
mult = int (n1*n2*n3)
div = float (n1/n2/n3)
print (f"La suma de los numeros es: {suma}")
print (f"La resta sucesiva es: {resta}")
print(f"La multiplicacion de los tres numeros es: {mult}")
print (f"La division consecutiva de los numeros es: {div}")
print (f"La division entera de los numeros es: {round(div)}")